baseURL = 'http://blog.ruanovanetworks.com'
languageCode = 'en-us'
title = 'My Homelab Blog'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "Welcome to My Homelab Blog"
  Content = "Sharing my homelab journey and tech experiments"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 10
